### ISSUE TITLE
Constant Disconnects while printing

### ISSUE THREAD

**Issue by idumzaes** [OctoPrint/OctoPrint-FixCBDFirmware#3]
I have a Tronxy XY-2 Pro and everything was working fine with OctoPrint until about a month or so ago.
Recently, I'm getting constant disconnects mid prints and having to start over, often doing from printer's built in SD card slot due to this issue.
Anyone else experiencing this? Perhaps it started after an OctoPrint/OctoPi update.

**Comment by foosel** [comment]
This is a question better suited for the community forums at community.octoprint.org rather than a plugin bug tracker.
