### ISSUE TITLE
Still warning about firmware after installed plugin

### ISSUE THREAD

**Issue by RubDubDuck** [OctoPrint/OctoPrint-FixCBDFirmware#5]
![image](https://user-images.githubusercontent.com/62017914/153720467-a7a6fa1d-c001-4e4b-b181-52f5169d445e.png)

**Comment by jneilliii** [comment]
Just to verify, did you restart OctoPrint once the plugin was installed?

**Comment by foosel** [comment]
Probably not, which would explain this behaviour. Closing, happy to reopen if a restart of OctoPrint and then reconnect doesn't actually fix this.
